### ISSUE TITLE
Jenkins Plugin Checkstyle is not able to work with relative pathes

### ISSUE THREAD

**Issue by webfeature** [Sweetchuck/scss_lint_reporter_checkstyle#1]
I'm using the checkstyle plugin in jenkins to visualize the linting errors. When i try to open a file via the checkstyle interface, i get following error:

> Copying the source file '../pathToFile' from the workspace to the build folder '6cdc80a3.tmp' on the Jenkins master failed. Seems that the path is relative, however an absolute path is required when copying the sources.

In the generated checkstyle.xml the path to the file is relativ, but the checkstyle plugin needs an absolute path:

Current state:
`<file name="../src/sass/file.scss">
    <error source="TrailingWhitespace" line="8" column="1" length="1" severity="warning" message="Line contains trailing whitespace" />
  </file>`

Target state:
`<file name="var/www/htdocs/project/src/sass/file.scss">
    <error source="TrailingWhitespace" line="8" column="1" length="1" severity="warning" message="Line contains trailing whitespace" />
  </file>`

I'm not a ruby programmer, could you deliver an checkstyle file with absolute pathes?

**Comment by Sweetchuck** [comment]
I have been used this gem with Jenkins, and I was facing this problem too, but I solved it by run the `scss-lint` command from the proper directory.

I have checked other linters such as PHP_CodeSniffer and PHP Mass Detector and they use absolute file paths in XML reports. So perhaps it is a good idea to use absolute file paths.

**Comment by Sweetchuck** [comment]
https://rubygems.org/gems/scss_lint_reporter_checkstyle/versions/0.2.0
